name: Maven Build on Push

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop, release/* ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package jacoco:report --file pom.xml -Daem.analyser.strict=true

    - name: Archive Jacoco reports
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-reports
        path: ${{ github.workspace }}/core/target/site/jacoco
